services:

  main-db:
    image: postgres
    restart: on-failure:1
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB


  blacklisted-jwts-db:
    image: redis/redis-stack
    restart: on-failure:1
    ports:
      - $REDIS_LOCAL_PORT:$REDIS_DOCKER_PORT


  mission-auth-service:
    depends_on:
      - main-db
      - blacklisted-jwts-db
    build:
      context: .
    restart: on-failure:1
    ports: 
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - SPRING_APPLICATION_JSON=$SPRING_APPLICATION_JSON
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:$POSTGRES_DOCKER_PORT/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_DATA_REDIS_HOST=blacklisted-jwts-db
      - SPRING_DATA_REDIS_PORT=$REDIS_DOCKER_PORT
        
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


